### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by hpfister** [msiniscalchi/atom-latextools#133]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.8.3

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:302

Error: spawn EACCES
    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:379:9)
    at exports.execFile (child_process.js:151:15)
    at module.(anonymous function) (ELECTRON_ASAR.js:184:20)
    at SkimViewer.module.exports.BaseViewer.runViewer (/Users/hpfister/.atom/packages/latextools/lib/viewers/base-viewer.coffee:22:7)
    at SkimViewer.module.exports.SkimViewer.viewFile (/Users/hpfister/.atom/packages/latextools/lib/viewers/skim-viewer.coffee:51:6)
    at Viewer.module.exports.Viewer.jumpToPdf (/Users/hpfister/.atom/packages/latextools/lib/viewer.coffee:75:16)
    at /Users/hpfister/.atom/packages/latextools/lib/builder.coffee:233:17
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

### Commands

```
     -0:43.5.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -0:29.2.0 latextools:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai-slate"
    ]
  },
  "latextools": {
    "forwardSync": false
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-bootstrap4, v1.4.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-monokai, v0.10.4 (inactive)
atom-terminal, v0.8.0 (inactive)
auto-update-packages, v1.0.1 (active)
autocomplete-bibtex, v0.6.2 (active)
color-picker, v2.2.2 (active)
git-plus, v5.18.0 (active)
hard-wrap, v1.1.0 (inactive)
language-latex, v1.0.0 (active)
language-sln, v0.1.0 (active)
latextools, v0.8.3 (active)
marked, v0.1.10 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
monokai-slate, v0.6.0 (active)
open-recent, v5.0.0 (active)
pdf-view, v0.50.0 (active)
pigments, v0.37.0 (active)
print-atom, v0.1.1 (inactive)
theme-switcher, v1.1.0 (active)
todo-show, v1.7.0 (inactive)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ig0774** [comment]
Thanks for the bug report. Sorry about that. I had tested the wrong code-path. Things should be working with v0.8.4.
