### ISSUE TITLE
Failed to load latextools, at duplicate key 'ctrl-l c'

### ISSUE THREAD

**Issue by JorgeGT** [msiniscalchi/atom-latextools#135]
I heard that Atom 1.12 beta had finally better international keyboard support, so I decided to give it a try to see if autorefs were correctly triggered. Instead, it seems I cannot load the package x) I tried to `unset!` the built-in `Ctrl-l` keymaps, but didn't help:

```
'atom-workspace atom-text-editor':
  'ctrl-l': 'unset!'
  'ctrl-l c': 'unset!'
  'ctrl-k ctrl-l': 'unset!'
```

Just reporting my stack trace in case it serves as an advanced warning of problems in future stable versions:

**Atom Version**: 1.12.0-beta0
**Electron Version**: 1.3.6
**System**:  Windows 10 (1607)
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.8.4
**Keyboard**: ES-ES

### Stack Trace

Failed to load the latextools package

```
At Duplicate key 'ctrl-l c'

Error: Duplicate key 'ctrl-l c'
  at Object.detectDuplicateKeys (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\season\lib\cson.js:268:13)
  at C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:115:38
  at Array.reduce (native)
  at Obj (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:107:30)
  at transformNode (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:197:12)
  at Value (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:79:14)
  at transformNode (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:197:12)
  at C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:114:17
  at Array.reduce (native)
  at Obj (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:107:30)
  at transformNode (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:197:12)
  at Value (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:79:14)
  at transformNode (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:197:12)
  at Block (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:76:14)
  at transformNode (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:197:12)
  at Object.parse (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\cson-parser\lib\parse.js:203:12)
  at parseObject (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\season\lib\cson.js:42:23)
  at parseContentsSync (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\season\lib\cson.js:68:16)
  at Object.readFileSync (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\node_modules\season\lib\cson.js:170:14)
  at C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\src\package.js:387:38
  at Array.map (native)
  at Package.module.exports.Package.loadKeymaps (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\src\package.js:384:46)
  at C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\src\package.js:110:19
  at Package.module.exports.Package.measure (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\src\package.js:92:15)
  at Package.module.exports.Package.load (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\src\package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\src\package-manager.js:466:14)
  at C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\src\package-manager.js:410:19
  at Config.module.exports.Config.transact (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\src\config.js:312:16)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\src\package-manager.js:405:19)
  at C:\Users\Jorge\AppData\Local\atom\app-1.12.0-beta0\resources\app.asar\src\atom-environment.js:763:28

```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
afterglow-monokai-syntax, v1.3.4 (inactive)
file-icons, v1.7.22 (inactive)
git-plus, v5.18.0 (inactive)
language-latex, v1.0.0 (inactive)
language-matlab, v0.2.1 (inactive)
latextools, v0.8.4 (inactive)
minimap, v4.25.0 (inactive)
monokai, v0.18.0 (inactive)
seti-monokai, v0.3.1 (inactive)
seti-ui, v1.3.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.0 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.3 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.102.2 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.46.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by ig0774** [comment]
Thanks for this report. We really shouldn't have that duplicate in there. It'll be removed shortly.

**Comment by JorgeGT** [comment]
Glad to be of any help, for the record I tested in Windows 8 and Ubuntu 14.04 and works OK, luckily with #115 now appearing to be solved with my keyboard (ES-ES).

**Comment by JorgeGT** [comment]
Confirming [v0.8.5](https://github.com/msiniscalchi/atom-latextools/tree/v0.8.5) fixes the issue.
