### ISSUE TITLE
Uncaught TypeError: warnings is not a function

### ISSUE THREAD

**Issue by dpo** [msiniscalchi/atom-latextools#16]
Line 629 in question should probably be `warnings.push(...)`?!

**Atom Version**: 1.4.0
**System**: Mac OS X 10.9.5
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.7.4

### Stack Trace

Uncaught TypeError: warnings is not a function

```
At /Users/dpo/.atom/packages/latextools/lib/parsers/parse-tex-log.coffee:629

TypeError: warnings is not a function
    at module.exports.parse_tex_log (/Users/dpo/.atom/packages/latextools/lib/parsers/parse-tex-log.coffee:629:5)
    at /Users/dpo/.atom/packages/latextools/lib/builder.coffee:162:30
    at ChildProcess.exithandler (child_process.js:222:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
  3x -0:18 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:17.3.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:16.8.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:16 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.4.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:15.2.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:14.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:13.2.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:09.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:08.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:07.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:06.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:06.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:06.0 core:save (atom-text-editor.editor.is-focused)
     -0:02.5.0 latextools:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "language-ruby-on-rails",
      "atom-pair",
      "language-gfm",
      "latex"
    ],
    "themes": [
      "atom-solarized-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "latextools": {
    "builderSettings": {
      "displayLog": true
    },
    "darwin": {},
    "linux": {},
    "win32": {}
  }
}
```

### Installed Packages

```coffee
# User
antialiased, v0.1.0
atom-solarized-dark-ui, v0.25.0
autocomplete-bibtex, v0.6.2
floobits, v0.30.0
indent-detective, v0.1.0
ink, v0.2.0
language-ampl, v0.2.0
language-cython, v0.3.0
language-diff, v0.4.0
language-fortran, v2.0.9
language-hombrew-formula, v1.0.2
language-julia, v0.5.0
language-latex, v0.6.1
language-matlab, v0.2.0
language-openmp, v0.2.0
latex-completions, v0.3.1
latextools, v0.7.4
linter, v1.11.3
linter-chktex, v1.2.4
linter-matlab, v1.1.0
linter-pep8, v1.2.1
linter-python-pep257, v0.0.1
linter-rubocop, v0.4.7
linter-write-good, v0.6.1
minimap, v4.19.0
minimap-git-diff, v4.1.8
python-autopep8, v0.1.3
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by msiniscalchi** [comment]
Thanks @dpo . Indeed there was a missing `push`. I just fixed it in master (it'll be part of the next release, which hopefully I will be able to do in a few days).

That said, that part of the code is only reached if log parsing fails in some way...

**Comment by dpo** [comment]
> That said, that part of the code is only reached if log parsing fails in some way...

Yes, but it happened in the first document I compiled.

Thanks.
