### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'D:/main.tex'

### ISSUE THREAD

**Issue by ReinholdSchmidt** [msiniscalchi/atom-latextools#174]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: SCHLAEPPI-PC
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package 0.8.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'D:\main.tex'

```
At fs.js:558

Error: ENOENT: no such file or directory, open 'D:\main.tex'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at parse_tex_directives (/packages/latextools/lib/parsers/tex-directive-parser.coffee:44:12)
    at Builder.module.exports.Builder.build (/packages/latextools/lib/builder.coffee:91:18)
    at /packages/latextools/lib/latextools.coffee:214:16)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.2/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.21.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.21.2/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.21.2/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:53.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -2:53.7.0 editor:newline (input.hidden-input)
     -2:50.7.0 core:save (input.hidden-input)
  2x -2:23.2.0 core:move-up (input.hidden-input)
  2x -2:22.8.0 editor:newline (input.hidden-input)
  2x -2:22.4.0 core:move-up (input.hidden-input)
     -2:21.8.0 core:paste (input.hidden-input)
     -2:12.9.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -2:10.7.0 core:confirm (input.hidden-input)
     -2:08.7.0 core:paste (input.hidden-input)
  5x -1:56.3.0 core:move-left (input.hidden-input)
 17x -1:55.3.0 core:delete (input.hidden-input)
     -0:50.8.0 latextools:build (input.hidden-input)
     -0:35.8.0 core:move-left (input.hidden-input)
     -0:33.9.0 core:save (input.hidden-input)
  2x -0:32.8.0 latextools:build (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.2 
erd 0.1.0 
git-plus 7.10.0 
language-latex 1.1.1 
latex 0.49.0 
latex-autocomplete 1.0.0 
latex-plus 0.9.1 
latexer 0.3.0 
latextools 0.8.5 
```

**Comment by ReinholdSchmidt** [comment]
no rootfile added
