### ISSUE TITLE
Uncaught Error: Command failed: osascript -e "POSIX path of (path to app id "net.sourceforge.skim...

### ISSUE THREAD

**Issue by tzm41** [msiniscalchi/atom-latextools#63]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.8.0

### Stack Trace

Uncaught Error: Command failed: osascript -e "POSIX path of (path to app id "net.sourceforge.skim-app.skim")"
33:34: syntax error: Expected “,” but found unknown token. (-2741)

```
At child_process.js:496

Error: Command failed: osascript -e "POSIX path of (path to app id "net.sourceforge.skim-app.skim")"
33:34: syntax error: Expected “,” but found unknown token. (-2741)

    at checkExecSyncError (child_process.js:453:13)
    at execSync (child_process.js:493:13)
    at SkimViewer.module.exports.SkimViewer.forwardSync (/Users/colin/.atom/packages/latextools/lib/viewers/skim-viewer.coffee:18:17)
    at Viewer.module.exports.Viewer.jumpToPdf (/Users/colin/.atom/packages/latextools/lib/viewer.coffee:65:16)
    at /Users/colin/.atom/packages/latextools/lib/builder.coffee:220:17
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:51.8.0 core:move-right (atom-text-editor.editor.is-focused)
  7x -1:49.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:40.7.0 latextools:dollar-sign (atom-text-editor.editor.is-focused)
     -1:39.8.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:36.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:10.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:10.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.6.0 latextools:dollar-sign (atom-text-editor.editor.is-focused)
  2x -1:00.6.0 core:backspace (atom-text-editor.editor.is-focused)
  7x -0:54.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:49.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:44.8.0 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
     -0:42.6.0 latextools:build (atom-text-editor.editor.is-focused)
     -0:15.9.0 editor:select-line (atom-text-editor.editor.is-focused)
     -0:15.9.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:02.8.0 latextools:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "latextools": {
    "builderSettings": {},
    "darwin": {},
    "linux": {},
    "win32": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-bibtex, v0.6.2
autocomplete-php, v0.3.7
autocomplete-python, v1.7.0
autocomplete-ruby, v0.1.0
color-picker, v2.1.1
file-icons, v1.6.18
git-diff-details, v0.23.0
language-hdl, v0.1.4
language-latex, v0.6.1
language-r, v0.4.0
language-x86, v0.1.0
latex, v0.32.0
latextools, v0.8.0
linter, v1.11.3
linter-chktex, v1.2.5
linter-javac, v1.8.1
minimap, v4.21.0
minimap-autohide, v0.10.1
minimap-bookmarks, v0.3.0
minimap-codeglance, v0.4.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
minimap-split-diff, v0.3.0
pdf-view, v0.50.0
pigments, v0.24.5
remote-edit, v1.8.24
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by ig0774** [comment]
Thanks for the error report. I've add a PR (#64) that will fix this specific error. Note, however, that [as the manual says](https://github.com/msiniscalchi/atom-latextools/blob/master/MANUAL.md#os-x) you'll need to have [Skim.app](http://skim-app.sourceforge.net/) installed for latextools to work properly or to change the viewer in the settings file to `"pdf-view"` to use the `pdf-view` plugin.
