### ISSUE TITLE
Uncaught TypeError: Cannot read property 'build' of null

### ISSUE THREAD

**Issue by tzm41** [msiniscalchi/atom-latextools#65]
[Enter steps to reproduce below:]

1. Open .tex file.
2. Press Command+Option+B to build.

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'build' of null

```
At /Users/colin/.atom/packages/latextools/lib/latextools.coffee:213

TypeError: Cannot read property 'build' of null
    at atom-text-editor.subscriptions.add.atom.commands.add.latextools:build (/Users/colin/.atom/packages/latextools/lib/latextools.coffee:213:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -9:17.2.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -9:11 core:backspace (atom-text-editor.editor.is-focused)
     -8:55.8.0 latextools:dollar-sign (atom-text-editor.editor.is-focused)
     -8:54 core:move-right (atom-text-editor.editor.is-focused)
     -8:53 latextools:dollar-sign (atom-text-editor.editor.is-focused)
     -8:50.4.0 core:move-right (atom-text-editor.editor.is-focused)
 16x -8:49.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:38.2.0 core:copy (atom-text-editor.editor.is-focused)
     -6:36.7.0 core:paste (atom-text-editor.editor.is-focused)
  2x -6:31.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -6:18.7.0 core:save (atom-text-editor.editor.is-focused)
     -6:16.6.0 settings-view:open (atom-text-editor.editor.is-focused)
     -6:13.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:17.1.0 latextools:build (atom-text-editor.editor.is-focused)
     -1:07.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:02.6.0 latextools:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ]
  },
  "latextools": {
    "builderSettings": {},
    "darwin": {},
    "linux": {},
    "viewer": "pdf-view",
    "win32": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-bibtex, v0.6.2
autocomplete-php, v0.3.7
autocomplete-python, v1.7.0
autocomplete-ruby, v0.1.0
color-picker, v2.1.1
file-icons, v1.6.18
git-diff-details, v0.23.0
language-hdl, v0.1.4
language-latex, v0.6.1
language-r, v0.4.0
language-x86, v0.1.0
latex, v0.32.0
latextools, v0.8.0
linter, v1.11.3
linter-chktex, v1.2.5
linter-javac, v1.8.1
minimap, v4.21.0
minimap-autohide, v0.10.1
minimap-bookmarks, v0.3.0
minimap-codeglance, v0.4.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
minimap-split-diff, v0.3.0
pdf-view, v0.50.0
pigments, v0.24.5
remote-edit, v1.8.24
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by ig0774** [comment]
This should be fixed in v0.8.2.
