### ISSUE TITLE
Failed to load the latextools package

### ISSUE THREAD

**Issue by MatteoRagni** [msiniscalchi/atom-latextools#7]
[Enter steps to reproduce below:]

1. Install **latextools**

**Atom Version**: 1.4.0
**System**: "Arch Linux"
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.7.2

### Stack Trace

Failed to load the latextools package

```
At Cannot find module './parsers/parseTeXLog'

Error: Cannot find module './parsers/parseTeXLog'
  at Module._resolveFilename (module.js:336:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:286:25)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/home/nirvana1289/.atom/packages/latextools/lib/builder.coffee:5:19)
  at Object.<anonymous> (/home/nirvana1289/.atom/packages/latextools/lib/builder.coffee:1:1)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/home/nirvana1289/.atom/packages/latextools/lib/latextools.coffee:2:11)
  at Object.<anonymous> (/home/nirvana1289/.atom/packages/latextools/lib/latextools.coffee:1:1)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:721:27)
  at /usr/share/atom/resources/app.asar/src/package.js:117:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:443:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:393:14)
  at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:684:21)
  at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
  at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
  at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/home/nirvana1289/workspace",
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "markdown-preview"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v1.0.5
autocomplete-bibtex, v0.6.2
autocomplete-plus, v2.25.0
figlet, v0.5.3
latextools, v0.7.2
markdown-preview-plus, v2.2.2
mathjax-wrapper, v0.1.0
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-selection, v4.3.1
pdf-view, v0.39.0
preview-inline, v0.5.1

# Dev
No dev packages
```

**Comment by msiniscalchi** [comment]
Actually, there was no Linux support until the latest version, 0.7.3. Things should now work. .

**Comment by MatteoRagni** [comment]
Thank you very much. On monday I will check on my setup.
