### ISSUE TITLE
Uncaught TypeError: atom.workspace.open(...).done is not a function

### ISSUE THREAD

**Issue by cars10** [msiniscalchi/atom-latextools#74]
[Enter steps to reproduce below:]

1. hit ctrl+alt+b to compile.

**Atom Version**: 1.6.2
**System**: "Manjaro Linux"
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.8.0

### Stack Trace

Uncaught TypeError: atom.workspace.open(...).done is not a function

```
At /home/cars10/.atom/packages/latextools/lib/viewers/atom-pdf-viewer.coffee:32

TypeError: atom.workspace.open(...).done is not a function
    at module.exports._open (/home/cars10/.atom/packages/latextools/lib/viewers/atom-pdf-viewer.coffee:32:7)
    at AtomPdfViewer.module.exports.AtomPdfViewer.forwardSync (/home/cars10/.atom/packages/latextools/lib/viewers/atom-pdf-viewer.coffee:39:5)
    at Viewer.module.exports.Viewer.jumpToPdf (/home/cars10/.atom/packages/latextools/lib/viewer.coffee:65:16)
    at /home/cars10/.atom/packages/latextools/lib/builder.coffee:220:17
    at ChildProcess.exithandler (child_process.js:206:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:17.9.0 recent-projects:open (div.package-detail.panels-item)
     -1:09.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -1:06.6.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:05.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:05.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:04.6.0 recent-projects:open (ul.list-inline.tab-bar.inset-panel)
     -1:03.7.0 core:cancel (div.recent-projects-view.pane-item.padded)
     -0:46.5.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -0:39.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:37.7.0 core:close (div.pdf-view)
     -0:35.2.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:34 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:31.8.0 latextools:build (atom-text-editor.editor.is-focused)
     -0:01.6.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:00.5.0 latextools:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "latextools": {
    "builderSettings": {},
    "darwin": {},
    "linux": {},
    "viewer": "pdf-view",
    "win32": {}
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.4.3
file-icons, v1.7.1
keyboard-localization, v1.4.16
language-latex, v0.6.1
latexer, v0.3.0
latextools, v0.8.0
pdf-view, v0.50.0
recent-projects, v0.9.5

# Dev
No dev packages
```

**Comment by cars10** [comment]
If someone is trying to reproduce - this worked 2 weeks ago. Then something updated on my system (nothing tex related) and it was broken. There where updates for alot of packages, i am sure it is related to an update of one of the following two:

http://manjaro.github.io/Update-2016-03-31_(stable)/
https://manjaro.github.io/Update-2016-04-07_(stable)/

The first one updated chromium, i think it is related to that, although i am not sure if atom even depends on it? The first one updated node, could also be related to that. check the "changelog" link at the bottom of the two to see the full list of updated packages. I currently have this error on 3 maschines, all running the latest manjaro.
